import AppKit
import Combine

/// Abstraction over the parts of `NSPasteboard` we touch, so restore and
/// transient-filtering can be unit-tested without the real system pasteboard.
protocol PasteboardReading {
    var changeCount: Int { get }
    var typeNames: [String] { get }
    func string(forType type: NSPasteboard.PasteboardType) -> String?
    func data(forType type: NSPasteboard.PasteboardType) -> Data?
}

protocol PasteboardWriting {
    func restore(_ item: ClipboardItem)
}

extension NSPasteboard: PasteboardReading {
    var typeNames: [String] { (types ?? []).map { $0.rawValue } }
}

/// Names of pasteboard types that signal an item should not be stored.
enum ClipboardPolicy {
    static let transientTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        // Password managers commonly mark items concealed:
        "com.agilebits.onepassword",
    ]

    /// Skip capture when any transient/concealed marker is present.
    static func shouldSkip(typeNames: [String]) -> Bool {
        !Set(typeNames).isDisjoint(with: transientTypes)
    }

    /// Cap stored image dimension to keep memory/disk bounded.
    static let maxImagePixelDimension: CGFloat = 1024
}

/// Live clipboard monitor. Polls `changeCount` off the main thread and captures
/// new copies. Never mutates the clipboard while monitoring.
@MainActor
final class ClipboardService: ObservableObject {
    @Published private(set) var history = ClipboardHistory()
    @Published var searchQuery: String = ""

    var isPaused: Bool = false
    var isPrivateMode: Bool = false

    private let pasteboard: PasteboardReading
    private let writer: PasteboardWriting
    private var lastChangeCount: Int
    private var timer: Timer?
    private let store: ClipboardPersistence

    init(pasteboard: PasteboardReading = NSPasteboard.general,
         writer: PasteboardWriting = SystemPasteboardWriter(),
         store: ClipboardPersistence = ClipboardPersistence(),
         maxItems: Int = 100) {
        self.pasteboard = pasteboard
        self.writer = writer
        self.store = store
        self.lastChangeCount = pasteboard.changeCount
        self.history = store.load() ?? ClipboardHistory()
        self.history.maxItems = maxItems
    }

    var filteredItems: [ClipboardItem] {
        history.search(searchQuery)
    }

    func updateMaxItems(_ value: Int) {
        history.maxItems = max(1, value)
        persist()
    }

    func startMonitoring() {
        guard timer == nil else { return }
        let t = Timer.scheduledTimer(withTimeInterval: 0.6, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.poll() }
        }
        t.tolerance = 0.2
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    func stopMonitoring() {
        timer?.invalidate()
        timer = nil
    }

    private func poll() {
        guard !isPaused, !isPrivateMode else {
            // Keep the change count in sync so we don't capture a backlog on resume.
            lastChangeCount = pasteboard.changeCount
            return
        }
        let current = pasteboard.changeCount
        guard current != lastChangeCount else { return }
        lastChangeCount = current
        capture()
    }

    /// Build an item from the current pasteboard contents and insert it.
    func capture() {
        let types = pasteboard.typeNames
        guard !ClipboardPolicy.shouldSkip(typeNames: types) else {
            Log.clipboard.debug("Skipping transient/concealed pasteboard item")
            return
        }
        guard let item = Self.makeItem(from: pasteboard, types: types,
                                       source: NSWorkspace.shared.frontmostApplication) else {
            return
        }
        history.insert(item)
        persist()
    }

    /// Pure-ish builder: given a reader + present types, produce an item.
    nonisolated static func makeItem(from pb: PasteboardReading,
                                     types: [String],
                                     source: NSRunningApplication?) -> ClipboardItem? {
        let set = Set(types)
        let sourceName = source?.localizedName
        let sourceBundle = source?.bundleIdentifier

        // File URLs first (Finder copies).
        if set.contains(NSPasteboard.PasteboardType.fileURL.rawValue),
           let str = pb.string(forType: .fileURL),
           let url = URL(string: str) {
            return ClipboardItem(kind: .fileURL,
                                 preview: url.lastPathComponent,
                                 stringContent: url.path,
                                 sourceAppName: sourceName,
                                 sourceBundleID: sourceBundle)
        }
        // Images.
        if set.contains(NSPasteboard.PasteboardType.png.rawValue) ||
           set.contains(NSPasteboard.PasteboardType.tiff.rawValue) {
            let raw = pb.data(forType: .png) ?? pb.data(forType: .tiff)
            if let raw, let png = downscaledPNG(from: raw) {
                return ClipboardItem(kind: .image,
                                     preview: "Image",
                                     imageData: png,
                                     sourceAppName: sourceName,
                                     sourceBundleID: sourceBundle)
            }
        }
        // Plain / rich text.
        if let str = pb.string(forType: .string), !str.isEmpty {
            let isURL = URL(string: str).map { $0.scheme != nil } ?? false
            let hasRTF = set.contains(NSPasteboard.PasteboardType.rtf.rawValue)
            return ClipboardItem(kind: isURL ? .url : (hasRTF ? .richText : .text),
                                 preview: String(str.prefix(400)),
                                 stringContent: str,
                                 sourceAppName: sourceName,
                                 sourceBundleID: sourceBundle)
        }
        return nil
    }

    /// Downscale large images to PNG bytes bounded by `maxImagePixelDimension`.
    nonisolated static func downscaledPNG(from raw: Data) -> Data? {
        guard let image = NSBitmapImageRep(data: raw) else { return nil }
        let width = CGFloat(image.pixelsWide)
        let height = CGFloat(image.pixelsHigh)
        let maxDim = ClipboardPolicy.maxImagePixelDimension
        guard width > maxDim || height > maxDim else {
            return image.representation(using: .png, properties: [:])
        }
        let scale = min(maxDim / width, maxDim / height)
        let newSize = NSSize(width: width * scale, height: height * scale)
        let target = NSBitmapImageRep(bitmapDataPlanes: nil,
                                      pixelsWide: Int(newSize.width),
                                      pixelsHigh: Int(newSize.height),
                                      bitsPerSample: 8, samplesPerPixel: 4,
                                      hasAlpha: true, isPlanar: false,
                                      colorSpaceName: .deviceRGB,
                                      bytesPerRow: 0, bitsPerPixel: 0)
        guard let target else { return image.representation(using: .png, properties: [:]) }
        target.size = newSize
        NSGraphicsContext.saveGraphicsState()
        NSGraphicsContext.current = NSGraphicsContext(bitmapImageRep: target)
        image.draw(in: NSRect(origin: .zero, size: newSize))
        NSGraphicsContext.restoreGraphicsState()
        return target.representation(using: .png, properties: [:])
    }

    // MARK: History mutations (also re-sync change count so restores aren't re-captured)

    func restore(_ item: ClipboardItem) {
        writer.restore(item)
        lastChangeCount = pasteboard.changeCount
    }

    func remove(_ item: ClipboardItem) { history.remove(id: item.id); persist() }
    func togglePin(_ item: ClipboardItem) { history.togglePin(id: item.id); persist() }
    func clearAll() { history.clearAll(); persist() }
    func clearUnpinned() { history.clearUnpinned(); persist() }

    private func persist() { store.save(history) }
}

/// Writes an item back to the system pasteboard.
struct SystemPasteboardWriter: PasteboardWriting {
    func restore(_ item: ClipboardItem) {
        let pb = NSPasteboard.general
        pb.clearContents()
        switch item.kind {
        case .image:
            if let data = item.imageData { pb.setData(data, forType: .png) }
        case .fileURL:
            if let path = item.stringContent {
                let url = URL(fileURLWithPath: path)
                pb.writeObjects([url as NSURL])
            }
        default:
            if let str = item.stringContent { pb.setString(str, forType: .string) }
        }
    }
}
